### ISSUE TITLE
Make line numbering optional

### ISSUE THREAD

**Issue by s-tikhomirov** [s-tikhomirov/solidity-latex-highlighting#5]
E.g., it doesn't make sense for very short code examples.

**Comment by koppor** [comment]
Does https://stackoverflow.com/a/44554181/873282 help here? Think, this is a feature of the [listings](https://ctan.org/pkg/listings?lang=de) package - and not something about your contribution, is it?

**Comment by s-tikhomirov** [comment]
Indeed. In case SO is unavailable, here is how you make a listing without line numbers:

```
\begin{lstlisting}[language=solidity,numbers=none]
```
